Archive (zip) option also found and corrected an HTTP 404 error
pe-st/garmin-connect-export pull request #57
Opened 2021-02-28 13:25 UTC by rsjrny

1) Fixed a 404 error caused when an activity listed does not exist

2) added a --archive option to create and merge downloaded activity files into a zip file.
after new activities are downloaded the zip file is expanded, new activities added so no duplicates exist, and then files are re-zipped.

2021-06-14 17:13 UTC, pe-st commented
Sorry for not responding earlier. It's quite a big change (two distinct features in one pull request), I wasn't able to test it yet. I have some doubts on some details (e.g. is it good practice to have to have a global variable `NOTEXIST` in upper case; I think the convention is rather lower case? Is it good practice at all to use a global variable here? And is the archiving/zipping part portable? There seem to be hardcoded Windows backslashes?)

2022-05-29 01:22 UTC, bxsx requested changes
I think this feature is beyond the scope of the app. While unzipping is required for the correct handling of _original_ files, further files processing should be done using dedicated software.

Adding this kind of functionality does not add much value to the application, but it can significantly increase maintenance costs.

However, in case we would like to merge this PR, there are at least a few issues that need to be addressed (after a quick change scan):
- global variables should be omitted
- the code must be cross-platform
- synchronization must be refactored (`time.sleep()`)

In general, I vote against this feature/PR.

2022-05-29 01:22 UTC, bxsx commented on gcexport.py
> +NOTEXIST = 0
This looks to be a variable, not a constant. Global variables shall be avoided.

2022-05-29 01:22 UTC, bxsx commented on gcexport.py
> +    time.sleep(3)
This is not reliable. You should use a more secure synchronization method.

2022-05-29 01:22 UTC, bxsx commented on gcexport.py
> +    temparch = dirpart + "\\temparch"
It doesn't look cross-platform. You should probably use `os.path.join()` instead.

2022-07-28 16:03 UTC, closed without merging